### ISSUE TITLE
quickwire.i2c module

### ISSUE THREAD

**Issue by mecaz** [speendo/raspi-mpd-lcd#1]
hello, i got following error when try to run your script. what should i do?

sudo python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from LCDController import *
  File "/home/pi/raspi-mpd-lcd/LCDController.py", line 3, in <module>
    from i2c_lcd_patched import i2c_lcd
  File "/home/pi/raspi-mpd-lcd/i2c_lcd_patched.py", line 6, in <module>
    from i2clibraries import i2c_lcd as i2c_lcd_prev
  File "/home/pi/raspi-mpd-lcd/i2clibraries/i2c_lcd.py", line 1, in <module>
    from i2clibraries import i2c
  File "/home/pi/raspi-mpd-lcd/i2clibraries/i2c.py", line 1, in <module>
    from quick2wire.i2c import I2CMaster, writing_bytes, reading
ImportError: No module named quick2wire.i2c

**Comment by speendo** [comment]
Hi!

The error you describe suggests that you don't have quick2wire installed. However, I doubt that it would work if you had it installed. The approach in this project is somehow broken...

I don't know about your project, but if you are just starting, I would suggest you stop using quick2wire (which is required for this script).

quick2wire stopped working for me several months ago. I then switched to wiringPi, however, recently this also stopped working with the current release of Raspbian.

My plan is now to build my own library to use a 2004 (or 1602) LCD.

Tell me about your project. Maybe we can work together?

**Comment by mecaz** [comment]
Hello,

I am planning to make a mpd music server with 20x4 screen that displays song and artist info on it.
But i couldnt make it happen. I am using latest volumio and rpi b and a i2c lcd screen.
My lcd displayed some static lines with that tutorial http://www.recantha.co.uk/blog/?p=4849#comments 
but i couldnt make it show dynamic text like mpd now playing info

**Comment by speendo** [comment]
I have a very similar project. I want to make a web radio receiver. In the first stage I only want it to switch on and off when the light goes on/out (I have a photocell for that) and a LCD screen that displays some information (time, song and artist info, radio station).

I got the part with the light switch working already. The lcd part was working as well, however the frameworks to control the lcd where "dying" away (first I used quick2wire, then I switched to wiringpi, both stopped working). I now plan to write an lcd driver myself.

The tutorial you linked is also the base for my current attempt, however, I want to understand what it is doing line by line.

Everything else (the dynamic text and reading the mpd info) is working already. Would you like to make a project together?

If you have any questions concerning my project (even if you don't want to work together), feel free to ask.

**Comment by speendo** [comment]
I wrote my own LCD library (driver).

The project still needs some cleanup but it should work now.

If you have the chance to test it, I'd be glad to know how it works for you.
